# Generated by Django 6.0.5 on 2026-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_type',
            field=models.CharField(default='SAP', max_length=50),
            preserve_default=False,
        ),
    ]
