# Generated by Django 6.0.5 on 2026-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_normalizedrecord_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='rawrecord',
            name='source',
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='source_type',
            field=models.CharField(default='SAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='RawRecord',
        ),
    ]
